service:
  name: serverless-aws-node-bootstrap
# app and org for use with dashboard.serverless.com
app: example
org: leovs09

plugins:
  - serverless-webpack
  - serverless-secrets-plugin

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SECRET_SERVICE_KEY: ${self:custom.secrets.SECRET_SERVICE_KEY}

custom:
  secrets: ${file(./secrets.${opt:stage, self:provider.stage}.yml)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
    enviroment:
      STAGE: ${self:provider.stage}
      SECRET_FUNCTION_TOKEN: ${env:SECRET_FUNCTION_TOKEN}
      
